#!/bin/bash

ARCH="${1}"
BINDINGS="${2}"
ANDROID_PLATFORM="android-28"
SRC="/home/src"
WORK="/tmp/build"
OUT="/home/output"

if [ ! -d "${SRC}" ]; then
    echo "Source tree missing. Mount opentxs source directory at ${SRC}"
    exit 1
fi

if [ ! -d "${OUT}" ]; then
    echo "Output directory missing. Mount output directory at ${OUT}"
    exit 1
fi

if [ "${ARCH}" == "" ]; then
    echo "Target architecture not set. Allowed values: arm64 arm x64 x86"
    exit 1
elif [ "${ARCH}" == "arm64" ]; then
    export ANDROID_ABI="arm64-v8a"
    export CMAKE_CROSSCOMPILING_EMULATOR="/usr/bin/qemu-aarch64-static"
    export CUSTOM_LDFLAGS="-Wl,-lGLESv2"
elif [ "${ARCH}" == "arm" ]; then
    export ANDROID_ABI="armeabi-v7a"
    export CMAKE_CROSSCOMPILING_EMULATOR="/usr/bin/qemu-arm-static"
    export CUSTOM_LDFLAGS="-Wl,-lGLESv2"
elif [ "${ARCH}" == "x64" ]; then
    export ANDROID_ABI="x86_64"
    export CMAKE_CROSSCOMPILING_EMULATOR=""
    export CUSTOM_LDFLAGS="-Wl,-lGLESv2"
elif [ "${ARCH}" == "x86" ]; then
    export ANDROID_ABI="x86"
    export CMAKE_CROSSCOMPILING_EMULATOR=""
    export CUSTOM_LDFLAGS="-Wl,-lGLESv2 -Wl,--no-warn-shared-textrel"
else
    echo "Unknown architecture: ${ARCH}"
    echo "Allowed values: arm64 arm x64 x86"
    exit 1
fi

if [ "${BINDINGS}" == "" ]; then
    export OT_QT="ON"
    echo "Enabling default bindings"
elif [ "${BINDINGS}" == "none" ]; then
    export OT_QT="OFF"
    echo "Disabling all bindings"
elif [ "${BINDINGS}" == "qt" ]; then
    export OT_QT="ON"
    echo "Enabling qt bindings"
elif [ "${BINDINGS}" == "all" ]; then
    export OT_QT="ON"
    echo "Enabling all bindings"
else
    echo "Unknown bindings: ${BINDINGS}"
    echo "Allowed values: none qt all"
    exit 1
fi

set -e

mkdir -p "${WORK}"
cd "${WORK}"
cmake \
    -GNinja \
    -DANDROID_ABI="${ANDROID_ABI}" \
    -DANDROID_PLATFORM="${ANDROID_PLATFORM}" \
    -DANDROID_STL="c++_shared" \
    -DCMAKE_TOOLCHAIN_FILE=/opt/ndk/build/cmake/android.toolchain.cmake \
    -DCMAKE_FIND_ROOT_PATH="/usr/android/${ARCH};/usr/qt-for-android" \
    -DCMAKE_CROSSCOMPILING_EMULATOR="${CMAKE_CROSSCOMPILING_EMULATOR}" \
    -DCMAKE_UNITY_BUILD=ON \
    -DBUILD_SHARED_LIBS=ON \
    -DProtobuf_PROTOC_EXECUTABLE=/usr/bin/protoc \
    -DOPENTXS_BUILD_TESTS=OFF \
    -DOT_WITH_QT="${OT_QT}" \
    -DOT_WITH_QML="${OT_QT}" \
    -DOT_OPENSSL_FLAVOR_LIBRESSL=ON \
    -DCMAKE_INSTALL_PREFIX="${OUT}" \
    -DCMAKE_SHARED_LINKER_FLAGS="${CUSTOM_LDFLAGS}" \
    -DCMAKE_EXE_LINKER_FLAGS="${CUSTOM_LDFLAGS}" \
    "${SRC}"
cmake --build .
rm -rf "${OUT}/"*
cmake --install .
cp -a "/usr/android/${ARCH}/include/google" "${OUT}/include/"
