#!/bin/bash

SRC="${1}"
#e.g. "-j 10 --output-on-failure --repeat until-pass:5 --timeout 300 --schedule-random"
CTEST_PARAMS="${2}"
WORK="/home/output"

if [ ! -d "${SRC}" ]; then
    echo "Source tree missing. Mount opentxs source directory at ${SRC}"
    exit 1
fi

if [ ! -d "${WORK}" ]; then
    echo "Work directory missing. Mount build directory at ${WORK}"
    exit 1
fi

if [ "${CTEST_PARAMS}" == "" ]; then
    echo "ctest params not set"
    exit 1
fi

set -e

cd "${WORK}"

echo ${CTEST_PARAMS}
ctest ${CTEST_PARAMS}
